### ISSUE TITLE
Report HTML and downloaded tables do not match

### ISSUE THREAD

**Issue by johnmous** [biopet/biopet#40]
In Carp pipeline, (and probably all our pipelines) there is an alignment table reporting the number of reads aligning, duplicates, etc. The alignment table I download with the "TSV file" button does not match the table shown in the HTML report. Numbers are off in the downloaded version because the duplicate and secondary reads are not counted as mapped.

See for instance ```/exports/sasc/project-193-rRNAdep_totalRNA/analysis/03_hg19_mcStayPaper/report/index.html```

**Comment by ffinfo** [comment]
This is correct because the tsv file is a stacked bar plot and the table below that shows the complete numbers.

For example, secondary reads are also aligned but in a stacked bar plot those reads should only count as secondary and not as mapped. If you sum of all columns this should be the same as the total number of reads, this is also tested.

I will change the name of the button to "Plot data", I can image this might be confusing. Wil continue on this in: BIOPET-627

**Comment by johnmous** [comment]
In any case, I would prefer the table shown in the HTML report to be identical to the downloaded one. So  the mapped reads there must also exclude the reads flagged as duplicates or secondary
